# Generated by Django 5.1 on 2025-01-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classiccardapplication',
            name='branch_location',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam Branch'), ('Trivandrum', 'Trivandrum Branch'), ('Kottayam', 'Kottayam Branch')], default='Ernakulam', max_length=50),
        ),
    ]
