# Generated by Django 5.1 on 2024-10-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_savingsaccountapplication_delete_accountstatement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='document',
            new_name='document_upload',
        ),
    ]
