# Generated by Django 5.1 on 2024-10-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='is_blocked',
        ),
    ]
