# Generated by Django 5.1 on 2025-01-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_classiccardapplication_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classiccardapplication',
            name='customer',
        ),
    ]
