# Generated by Django 5.1 on 2024-10-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_document_customer_document_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsAccountApplication',
        ),
    ]
