# Generated by Django 5.1 on 2025-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_classiccardapplication_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='classiccardapplication',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
