# Generated by Django 5.1 on 2024-10-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_savingsaccountapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
