# Generated by Django 5.1 on 2024-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_account_number_savings_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
