# Generated by Django 5.1 on 2024-10-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
