# Generated by Django 5.1 on 2024-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savings',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
