# Generated by Django 5.1.1 on 2024-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_loanofficer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
        migrations.AddField(
            model_name='current',
            name='account_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='current',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='savings',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='account_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
