# Generated by Django 5.1.1 on 2024-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
