# Generated by Django 5.1.1 on 2024-11-02 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='next_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
