# Generated by Django 5.1.1 on 2024-11-02 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_loan_balance_due_loan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Transaction Date & Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ifsc_code',
            field=models.CharField(default='AB12', max_length=11, verbose_name='IFSC Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_number',
            field=models.CharField(default=0, max_length=20, verbose_name="Receiver's Account Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], default='SAVINGS', max_length=10, verbose_name="Type of Receiver's Account"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(default='hello', max_length=100, verbose_name="Receiver's Full Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.TextField(default='test', verbose_name='Purpose of Transfer'),
            preserve_default=False,
        ),
    ]
