# Generated by Django 5.1 on 2025-03-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_customer_transaction_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, null=True, unique=True)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport')], max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('document_file', models.FileField(upload_to='kyc_documents/')),
                ('selfie', models.ImageField(null=True, upload_to='kyc_selfies/')),
                ('address_proof', models.FileField(null=True, upload_to='address_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
    ]
