# Generated by Django 5.1.1 on 2024-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
