# Generated by Django 5.1 on 2025-03-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_current_created_at_fixeddeposit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixeddeposit',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='duration_months',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='fixeddeposit',
            table=None,
        ),
    ]
