# Generated by Django 5.1.1 on 2024-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_current_balance_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_account_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
