# Generated by Django 5.1.1 on 2024-11-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_transaction_owner_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='owner_account_number',
            field=models.CharField(max_length=20, verbose_name="Customer's Account Number"),
        ),
    ]
