# Generated by Django 5.1.1 on 2024-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_transaction_owner_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
