# Generated by Django 5.1.1 on 2024-11-04 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_transaction_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField(editable=False)),
                ('maturity_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Fixed',
        ),
    ]
