# Generated by Django 5.1 on 2024-11-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_fixeddeposit_delete_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
